/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutQuizRouteImport } from './routes/_layout/quiz'
import { Route as LayoutDocRouteImport } from './routes/_layout/doc'
import { Route as LayoutLayoutNotesCreateBisRouteImport } from './routes/_layout/_layout.notes/createBis'
import { Route as LayoutLayoutNotesCreateRouteImport } from './routes/_layout/_layout.notes/create'
import { Route as LayoutLayoutNotesIdRouteImport } from './routes/_layout/_layout.notes/$id'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuizRoute = LayoutQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocRoute = LayoutDocRouteImport.update({
  id: '/doc',
  path: '/doc',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLayoutNotesCreateBisRoute =
  LayoutLayoutNotesCreateBisRouteImport.update({
    id: '/_layout/notes/createBis',
    path: '/notes/createBis',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutLayoutNotesCreateRoute = LayoutLayoutNotesCreateRouteImport.update({
  id: '/_layout/notes/create',
  path: '/notes/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLayoutNotesIdRoute = LayoutLayoutNotesIdRouteImport.update({
  id: '/_layout/notes/$id',
  path: '/notes/$id',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/doc': typeof LayoutDocRoute
  '/quiz': typeof LayoutQuizRoute
  '/notes/$id': typeof LayoutLayoutNotesIdRoute
  '/notes/create': typeof LayoutLayoutNotesCreateRoute
  '/notes/createBis': typeof LayoutLayoutNotesCreateBisRoute
}
export interface FileRoutesByTo {
  '/doc': typeof LayoutDocRoute
  '/quiz': typeof LayoutQuizRoute
  '/': typeof LayoutIndexRoute
  '/notes/$id': typeof LayoutLayoutNotesIdRoute
  '/notes/create': typeof LayoutLayoutNotesCreateRoute
  '/notes/createBis': typeof LayoutLayoutNotesCreateBisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/doc': typeof LayoutDocRoute
  '/_layout/quiz': typeof LayoutQuizRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_layout/notes/$id': typeof LayoutLayoutNotesIdRoute
  '/_layout/_layout/notes/create': typeof LayoutLayoutNotesCreateRoute
  '/_layout/_layout/notes/createBis': typeof LayoutLayoutNotesCreateBisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/doc'
    | '/quiz'
    | '/notes/$id'
    | '/notes/create'
    | '/notes/createBis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/doc'
    | '/quiz'
    | '/'
    | '/notes/$id'
    | '/notes/create'
    | '/notes/createBis'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/doc'
    | '/_layout/quiz'
    | '/_layout/'
    | '/_layout/_layout/notes/$id'
    | '/_layout/_layout/notes/create'
    | '/_layout/_layout/notes/createBis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/quiz': {
      id: '/_layout/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof LayoutQuizRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/doc': {
      id: '/_layout/doc'
      path: '/doc'
      fullPath: '/doc'
      preLoaderRoute: typeof LayoutDocRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_layout/notes/createBis': {
      id: '/_layout/_layout/notes/createBis'
      path: '/notes/createBis'
      fullPath: '/notes/createBis'
      preLoaderRoute: typeof LayoutLayoutNotesCreateBisRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_layout/notes/create': {
      id: '/_layout/_layout/notes/create'
      path: '/notes/create'
      fullPath: '/notes/create'
      preLoaderRoute: typeof LayoutLayoutNotesCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_layout/notes/$id': {
      id: '/_layout/_layout/notes/$id'
      path: '/notes/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof LayoutLayoutNotesIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutDocRoute: typeof LayoutDocRoute
  LayoutQuizRoute: typeof LayoutQuizRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutLayoutNotesIdRoute: typeof LayoutLayoutNotesIdRoute
  LayoutLayoutNotesCreateRoute: typeof LayoutLayoutNotesCreateRoute
  LayoutLayoutNotesCreateBisRoute: typeof LayoutLayoutNotesCreateBisRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDocRoute: LayoutDocRoute,
  LayoutQuizRoute: LayoutQuizRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutLayoutNotesIdRoute: LayoutLayoutNotesIdRoute,
  LayoutLayoutNotesCreateRoute: LayoutLayoutNotesCreateRoute,
  LayoutLayoutNotesCreateBisRoute: LayoutLayoutNotesCreateBisRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
